language: julia
os:
  - linux
julia:
  - nightly
notifications:
  email: false
git:
  depth: 999999 # for travis
env:
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - OPTIONS=$(julia -e 'isdefined(Base.JLOptions(), :use_compilecache) && print("--compilecache=no")')
  - julia $OPTIONS -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("ArbFloats"); Pkg.test("ArbFloats"; coverage=true)';
after_success:
  - julia -e 'using Pkg;cd(Pkg.dir("ArbFloats")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
  - julia -e 'using Pkg;cd(Pkg.dir("ArbFloats")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
